set workflow as failed when ansible apply failed

diff --git a/.github/workflows/ansible-playbook-cd.yaml b/.github/workflows/ansible-playbook-cd.yaml
--- a/.github/workflows/ansible-playbook-cd.yaml
+++ b/.github/workflows/ansible-playbook-cd.yaml
@@ -47,7 +47,9 @@ jobs:
         playbooks: ${{ fromJson(needs.list-ansible-playbooks.outputs.baremetals_playbooks) }}
     steps:
       - name: Apply ansible changes
+        id: ansible-apply
         run: ansible-playbook ${{ matrix.playbooks }}/*.yaml | tee ansible_apply.txt
+        continue-on-error: true
       - name: Add playbook path for identification
         run: echo "${{ matrix.playbooks }}" >> ansible_diff.txt
       - name: Post comment of ansible apply result
@@ -55,3 +57,8 @@ jobs:
         with:
           issue-number: ${{ github.event.pull_request.number }}
           body-path: 'ansible_apply.txt'
+      - name: State workflow to fail
+        if: steps.ansible-apply.outcome == 'failure'
+        run: |
+          echo "Ansible apply failed"
+          exit 1
