Gcp-start (#440)
* deploy vpc to gcp

* deploy gke cluster

* fix invalid capital character in tag key

* allow kubectl access from Macbook via dns endpoint

* fix terraform state address for github repo terrafrom

* convert internal services from IP address to fqdn

* fix grafana local domain

* delete disable kubernetes manifest for now

* fix loki domain variable

diff --git a/.github/workflows/fluxcd-ci.yaml b/.github/workflows/fluxcd-ci.yaml
--- a/.github/workflows/fluxcd-ci.yaml
+++ b/.github/workflows/fluxcd-ci.yaml
@@ -1,42 +1,42 @@
-name: Check kubernetes manifest
-on:
-  pull_request:
-    branches:
-      - main
-    paths:
-      - "kubernetes-manifest/**"
-permissions:
-  pull-requests: write
-  packages: read
-env:
-  NO_COLOR: "1"
+# name: Check kubernetes manifest
+# on:
+#   pull_request:
+#     branches:
+#       - main
+#     paths:
+#       - "kubernetes-manifest/**"
+# permissions:
+#   pull-requests: write
+#   packages: read
+# env:
+#   NO_COLOR: "1"
 
-jobs:
-  check_manifest_diff:
-    runs-on: laptop1
-    defaults:
-      run:
-        shell: bash -eo pipefail {0}
-    steps:
-      - name: Checkout Code
-        uses: actions/checkout@v4
-      - name: Check manifest diff
-        id: manifest-diff
-        continue-on-error: true
-        run: |
-          flux diff kustomization jagatku-manifest-selection --path kubernetes-manifest/ 2>&1 | tee flux_diff.txt
-      - name: Prepare PR comment format
-        run: |
-          echo "\`\`\`diff" >> flux_diff.md
-          cat flux_diff.txt >> flux_diff.md
-          echo "\`\`\`" >> flux_diff.md
-      - name: Post comment of check diff result
-        uses: peter-evans/create-or-update-comment@v5
-        with:
-          issue-number: ${{ github.event.pull_request.number }}
-          body-path: ./flux_diff.md
-      - name: State workflow to fail
-        if: steps.manifest-diff.outcome == 'failure'
-        run: |
-          echo "Kubernetes new manifest fail"
-          exit 1
+# jobs:
+#   check_manifest_diff:
+#     runs-on: laptop1
+#     defaults:
+#       run:
+#         shell: bash -eo pipefail {0}
+#     steps:
+#       - name: Checkout Code
+#         uses: actions/checkout@v4
+#       - name: Check manifest diff
+#         id: manifest-diff
+#         continue-on-error: true
+#         run: |
+#           flux diff kustomization jagatku-manifest-selection --path kubernetes-manifest/ 2>&1 | tee flux_diff.txt
+#       - name: Prepare PR comment format
+#         run: |
+#           echo "\`\`\`diff" >> flux_diff.md
+#           cat flux_diff.txt >> flux_diff.md
+#           echo "\`\`\`" >> flux_diff.md
+#       - name: Post comment of check diff result
+#         uses: peter-evans/create-or-update-comment@v5
+#         with:
+#           issue-number: ${{ github.event.pull_request.number }}
+#           body-path: ./flux_diff.md
+#       - name: State workflow to fail
+#         if: steps.manifest-diff.outcome == 'failure'
+#         run: |
+#           echo "Kubernetes new manifest fail"
+#           exit 1
