continue on error when checking kubernetes manifest

diff --git a/.github/workflows/fluxcd-ci.yaml b/.github/workflows/fluxcd-ci.yaml
--- a/.github/workflows/fluxcd-ci.yaml
+++ b/.github/workflows/fluxcd-ci.yaml
@@ -22,6 +22,7 @@ jobs:
         uses: actions/checkout@v4
       - name: Check manifest diff
         id: manifest-diff
+        continue-on-error: true
         run: |
           flux diff kustomization jagatku-manifest-selection --path kubernetes-manifest/ 2>&1 | tee flux_diff.txt
       - name: Post comment of check diff result
@@ -29,3 +30,8 @@ jobs:
         with:
           issue-number: ${{ github.event.pull_request.number }}
           body-path: ./flux_diff.txt"
+      - name: State workflow to fail
+        if: steps.manifest-diff.outcome == 'failure'
+        run: |
+          echo "Kubernetes new manifest fail"
+          exit 1
