post terraform plan and apply result to PR even when failed

diff --git a/.github/workflows/terraform-config-cd.yaml b/.github/workflows/terraform-config-cd.yaml
--- a/.github/workflows/terraform-config-cd.yaml
+++ b/.github/workflows/terraform-config-cd.yaml
@@ -60,11 +60,13 @@ jobs:
             GITHUB_TOKEN: ${{ github.token }}
         run: terraform init
       - name: Terraform apply
+        id: tfapply
         working-directory: ./${{ matrix.terraforms }}
         env:
             TF_VAR_token: ${{ secrets.GH_PAT }}
             TF_CLI_ARGS: "-no-color"
         run: terraform apply -auto-approve | tee apply.txt
+        continue-on-error: true
       - name: Prepend playbook path for identification
         working-directory: ./${{ matrix.terraforms }}
         run: echo "${{ matrix.terraforms }}" >> terraform_apply.md
@@ -83,3 +85,8 @@ jobs:
         with:
           issue-number: ${{ github.event.pull_request.number }}
           body-path: './${{ matrix.terraforms }}/terraform_apply.md'
+      - name: State workflow to fail
+        if: steps.tfapply.outcome == 'failure'
+        run: |
+          echo "Terraform apply failed"
+          exit 1
diff --git a/.github/workflows/terraform-config-ci.yaml b/.github/workflows/terraform-config-ci.yaml
--- a/.github/workflows/terraform-config-ci.yaml
+++ b/.github/workflows/terraform-config-ci.yaml
@@ -56,11 +56,13 @@ jobs:
             GITHUB_TOKEN: ${{ github.token }}
         run: terraform init
       - name: Terraform plan
+        id: tfplan
         working-directory: ./${{ matrix.terraforms }}
         env:
             TF_VAR_token: ${{ github.token }}
             TF_CLI_ARGS: "-no-color"
         run: terraform plan | tee plan.txt
+        continue-on-error: true
       - name: Prepend playbook path for identification
         working-directory: ./${{ matrix.terraforms }}
         run: echo "${{ matrix.terraforms }}" >> terraform_plan.md
@@ -79,3 +81,8 @@ jobs:
         with:
           issue-number: ${{ github.event.pull_request.number }}
           body-path: './${{ matrix.terraforms }}/terraform_plan.md'
+      - name: State workflow to fail
+        if: steps.tfplan.outcome == 'failure'
+        run: |
+          echo "Terraform plan failed"
+          exit 1
